---
chapter: 2
knit: "bookdown::render_book"
---

# Preproceso {#ch:preprocess}

Sección donde explicaremos el preproceso que se realizó a la base de datos.


## Reporte de Calidad de Datos {#sec:dqr}

Se pueden poner tablas, cálculos, lo que queramos.

A continuación un texto con referencias como ejemplo. Ésto obviamente lo quitaremos.


*Exponential smoothing was originally developed in the late 1950s [@Brown59;@Brown63;@Holt57;@Winters60]. Because of their computational simplicity and interpretability, they became widely used in practice.*

*Empirical studies by @MH79 and @Metal82 found little difference in forecast accuracy between exponential smoothing and ARIMA models. This made the family of exponential smoothing procedures an attractive proposition [see @CKOS01].*

*The methods were less popular in academic circles until  @OKS97 introduced a state space formulation of some of the methods, which was extended in @HKSG02 to cover the full range of exponential smoothing methods.*


